import {
  AlertTriangle,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Loader2,
  LogOut,
  MailCheck,
  MailX,
  Moon,
  Plus,
  Search,
  Send,
  SlidersHorizontal,
  Sun,
  Table2,
  User,
  type LucideProps,
} from "lucide-react"

export const Icons = {
  warning: AlertTriangle,
  filter: SlidersHorizontal,
  right: ChevronRight,
  left: ChevronLeft,
  send: Send,
  light: Sun,
  dark: Moon,
  check: Check,
  upDown: ChevronsUpDown,
  search: Search,
  user: User,
  table: Table2,
  signout: LogOut,
  emailVerified: MailCheck,
  emailNotVerified: MailX,
  add: Plus,
  spinner: Loader2,
}
